#include "Building.Static.h"

QList< RBuildingDefault> BuildingStatic::_DefaultBuildings = {
  {EBuildingIndex::Castle , EBuilding::Castle, 1},
  {EBuildingIndex::Build_1051 , EBuilding::None},
  {EBuildingIndex::ArrowTowerL , EBuilding::ArrowTower, 1},
  {EBuildingIndex::WallGate ,EBuilding::Wall ,1},   
  {EBuildingIndex::ArrowTowerR, EBuilding::ArrowTower}, 
  {EBuildingIndex::WatchTower, EBuilding::WatchTower},
  {EBuildingIndex::Build_1056, EBuilding::None},
  {EBuildingIndex::Build_1057, EBuilding::None},
  {EBuildingIndex::Build_1058, EBuilding::None},
  {EBuildingIndex::Build_1059, EBuilding::None},
  {EBuildingIndex::Build_1060, EBuilding::None},
  {EBuildingIndex::Build_1061, EBuilding::None},
  {EBuildingIndex::Build_1062, EBuilding::None},
  {EBuildingIndex::Build_1063, EBuilding::None},
  {EBuildingIndex::Build_1064, EBuilding::None},
  {EBuildingIndex::Build_1067, EBuilding::None},
  {EBuildingIndex::Build_1100, EBuilding::None},
  {EBuildingIndex::Build_1101, EBuilding::None},
  {EBuildingIndex::Build_1102, EBuilding::None},
  {EBuildingIndex::Build_1103, EBuilding::None},
  {EBuildingIndex::Build_1104, EBuilding::None},
  {EBuildingIndex::Build_1105, EBuilding::None},
  {EBuildingIndex::Build_1106, EBuilding::None},
  {EBuildingIndex::Build_1107, EBuilding::None},
  {EBuildingIndex::Build_1108, EBuilding::None},
  {EBuildingIndex::Build_1109, EBuilding::None},
  {EBuildingIndex::Build_1110, EBuilding::None},
  {EBuildingIndex::Build_1111, EBuilding::None},
  {EBuildingIndex::Build_1112, EBuilding::None},
  {EBuildingIndex::Build_1113, EBuilding::None},
  {EBuildingIndex::Build_1114, EBuilding::None},
  {EBuildingIndex::Build_1115, EBuilding::None},
  {EBuildingIndex::Build_1116, EBuilding::None},
  {EBuildingIndex::Build_1117, EBuilding::None},
  {EBuildingIndex::Build_1118, EBuilding::None},
  {EBuildingIndex::Build_1119, EBuilding::None},
  {EBuildingIndex::Build_1120, EBuilding::None},
  {EBuildingIndex::Build_1121, EBuilding::None},
  {EBuildingIndex::Build_1122, EBuilding::None},
  {EBuildingIndex::Build_1123, EBuilding::None},
  {EBuildingIndex::Build_1124, EBuilding::None},
  {EBuildingIndex::Build_1125, EBuilding::None},
  {EBuildingIndex::Build_1126, EBuilding::None},
  {EBuildingIndex::Build_1127, EBuilding::None},
  {EBuildingIndex::Build_1128, EBuilding::None},
  {EBuildingIndex::Build_1129, EBuilding::None},
  {EBuildingIndex::Build_1130, EBuilding::None},
  {EBuildingIndex::Build_1131, EBuilding::None},
  {EBuildingIndex::Build_1132, EBuilding::None},
  {EBuildingIndex::Build_1133, EBuilding::None},
  {EBuildingIndex::Build_1134, EBuilding::None},
  {EBuildingIndex::MaterialWorkShop ,EBuilding::MaterialWorkShop, 1},
  {EBuildingIndex::Crystal , EBuilding::CrystalMine, 1},
  {EBuildingIndex::Gangkou , EBuilding::Port, 1},
  {EBuildingIndex::Miracle , EBuilding::Miracle, 1},
  {EBuildingIndex::ElitePalace, EBuilding::ElitePalace, 1},
  {EBuildingIndex::Prison, EBuilding::Prison, 1},
  {EBuildingIndex::TrainHall, EBuilding::TrainHall, 1},
  {EBuildingIndex::StarBraveStatue, EBuilding::StarBraveStatue, 1},
  {EBuildingIndex::NebulaHall,EBuilding::None },
  {EBuildingIndex::Merchant, EBuilding::CargoShip, 1},
  {EBuildingIndex::TroopFlag, EBuilding::TroopDetails, 1},
  {EBuildingIndex::LeisureCenter ,EBuilding::LeisureHouse, 1},
  {EBuildingIndex::HuoChuang, EBuilding::Merchant, 1},
  {EBuildingIndex::PetCenter , EBuilding::PetHouse, 1},
  {EBuildingIndex::ResurrectionHall ,EBuilding::ResurrectionHall, 1},
  {EBuildingIndex::ServiceCenter, EBuilding::ServiceCenter, 1},
  {EBuildingIndex::EpicBattle, EBuilding::EpicBattle, 1},
  {EBuildingIndex::Monument, EBuilding::Monument, 1},
  {EBuildingIndex::Mastery , EBuilding::Mastery, 1},
  {EBuildingIndex::CommandHall, EBuilding::HallOfWar, 1},
  {EBuildingIndex::MagicLamp, EBuilding::None},
  {EBuildingIndex::LockArea_1 , EBuilding::AreaLock_1221, 1},
  {EBuildingIndex::LockArea_2 , EBuilding::AreaLock_1222, 1},
  {EBuildingIndex::LockArea_3, EBuilding::AreaLock_1222, 1},
  {EBuildingIndex::LockArea_4 , EBuilding::AreaLock_1222, 1}
};

BuildingStatic *BuildingStatic::Get(){
  static BuildingStatic *lInstance = nullptr;
  if(lInstance == nullptr){
    lInstance = new BuildingStatic();
    lInstance->Init();
  }
  return lInstance;
}

void BuildingStatic::Init(){}